services:
  backend:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: backend
    ports: 
      - "${API_PORT}:8000"
    command: "uvicorn --factory application.api.main:create_app --reload --host 0.0.0.0 --port 8000"
    env_file:
      - ../.env
    volumes:
      - ../app/:/app/
    networks:
      - backend-dev

networks:
  backend-dev:
    external: true
    driver: bridge