name: Update Documentation
on:
  push:
    branches:
      - main
      - infra
    paths:
      - 'docs/**'
      - '*.md'
  pull_request:
    branches:
      - main
      - infra
    paths:
      - 'docs/**'
      - '*.md'
  workflow_dispatch:

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3